name: Build Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install --force

      - name: Run build script
        run: npm run build

      - name: Run packaging script
        run: node ./scripts/pkg-win.js

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: out/win/

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          gh release create "v$(date +%Y%m%d%H%M%S)" --title "Windows Build Release" --notes "Automated Windows build from run ${{ github.run_number }}"
          gh release upload "v$(date +%Y%m%d%H%M%S)" out/win/* --clobber

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        run: |
          gh pr comment ${{ github.event.number }} --body "Windows build artifact is available in this run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
