name: Build Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install --force

      - name: Run build script
        run: npm run build

      - name: Run packaging script
        run: node ./scripts/pkg-win.js

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: out/win/

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          $KEY = "v" + (Get-Date -Format "yyyyMMddHHmmss")
          gh release create $KEY --title "Windows Build Release" --notes "Automated Windows build from run ${{ github.run_number }}"
          gh release upload $KEY out/win/* --clobber

      - name: Comment PR with artifact URLs
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });

            let comment = '🦾 New builds of the game ready to play:\n';
            for (const artifact of artifacts.data.artifacts) {
              const download_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts/${artifact.id}`;
              comment += `- [${artifact.name}](${download_url})\n`;
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment,
            });
